SELECT CURRENT_USER();
SELECT CURRENT_ROLE();
SELECT CURRENT_WAREHOUSE();
SELECT CURRENT_DATABASE();
SELECT CURRENT_SCHEMA();


CREATE OR REPLACE DATABASE COLLEGE_DB;

USE DATABASE COLLEGE_DB;

CREATE OR REPLACE SCHEMA EDUCATION_SCHEMA;

USE SCHEMA EDUCATION_SCHEMA;

CREATE OR REPLACE WAREHOUSE TRAINING_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE TRAINING_WH;


CREATE OR REPLACE TABLE STUDENTS (
    STUDENT_ID INT,
    STUDENT_NAME STRING,
    STREAM STRING,
    SCORE INT
);

CREATE OR REPLACE STAGE COLLEGE_STAGE;


SHOW DATABASES;
SHOW SCHEMAS;
SHOW WAREHOUSES;
SHOW TABLES;
SHOW STAGES;


INSERT INTO STUDENTS VALUES
(301, 'Rahul', 'CSE', 85),
(302, 'Ananya', 'ECE', 89),
(303, 'Rohan', 'IT', 78);

SELECT * FROM STUDENTS;


UPDATE STUDENTS
SET SCORE = 95
WHERE STUDENT_ID = 302;

SELECT * FROM STUDENTS;


DELETE FROM STUDENTS
WHERE STUDENT_ID = 303;

SELECT * FROM STUDENTS;


CREATE OR REPLACE TABLE STUDENT_PERFORMANCE (
    GENDER STRING,
    RACE_ETHNICITY STRING,
    PARENTAL_LEVEL_OF_EDUCATION STRING,
    LUNCH STRING,
    TEST_PREPARATION_COURSE STRING,
    MATH_SCORE INT,
    READING_SCORE INT,
    WRITING_SCORE INT
);

LIST @COLLEGE_STAGE;


CREATE OR REPLACE FILE FORMAT STUDENT_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


COPY INTO STUDENT_PERFORMANCE
FROM @COLLEGE_STAGE/StudentsPerformance.csv
FILE_FORMAT = STUDENT_CSV_FORMAT;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM STUDENT_PERFORMANCE;

SELECT *
FROM STUDENT_PERFORMANCE
LIMIT 10;


CREATE OR REPLACE TABLE EMPLOYEES (
    EMPLOYEE_ID INT,
    EMPLOYEE_NAME STRING,
    SALARY INT
);

INSERT INTO EMPLOYEES VALUES
(11, 'Karthik', 54000),
(12, 'Divya', 63000),
(13, 'Sanjay', 58000);

SELECT * FROM EMPLOYEES;


UPDATE EMPLOYEES
SET SALARY = 75000
WHERE EMPLOYEE_ID = 11;

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID = 13;

SELECT * FROM EMPLOYEES;


SELECT *
FROM EMPLOYEES
AT(OFFSET => -60);


INSERT INTO EMPLOYEES
SELECT *
FROM EMPLOYEES
AT(OFFSET => -60)
WHERE EMPLOYEE_ID = 13;

SELECT * FROM EMPLOYEES;
